# Generated by Django 4.2.2 on 2023-06-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Protein',
            new_name='protein',
        ),
    ]
